### PR TITLE
Andrew Kolumbic

### PR DESCRIPTION
**Pull request by AKolumbic**

### CODE REVIEW

**Comment by ghost** [comment]
Were you able to successfully test the endpoints?

**Comment by ghost** [comment]
hahaha That commit comment! Hows it going?

**Comment by AKolumbic** [comment]
Everything worked well, all tests worked in Postman. That last commit had two lines I changed, but i honestly didn't remember what it was haha.

**Comment by ghost** [comment]
You can tell when you click on them (commits). :) Glad to hear you tested, I'm just trying to be thorough.

**Pull request closed without merging**
